# Generated by Django 5.2 on 2025-04-10 15:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nono_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepixels',
            name='source_url',
            field=models.URLField(unique=True),
        ),
        migrations.CreateModel(
            name='NonogramPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('row_hints', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('column_hints', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('solution', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle', to='nono_app.imagepixels')),
            ],
        ),
    ]
