# Generated by Django 5.2 on 2025-04-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nono_app', '0002_alter_imagepixels_source_url_nonogrampuzzle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonogrampuzzle',
            name='column_hints',
        ),
        migrations.RemoveField(
            model_name='nonogrampuzzle',
            name='row_hints',
        ),

        migrations.AddField(
            model_name='nonogrampuzzle',
            name='column_hints',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonogrampuzzle',
            name='row_hints',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
